version: "3.8"
services:
  backend:
    build: ../backend
    environment:
      - PORT=4000
      - JWT_SECRET=change-me
    ports: ["4000:4000"]
  frontend:
    build: ../frontend
    environment:
      - NEXT_PUBLIC_API=http://localhost:4000
    ports: ["3000:3000"]
